fix: number input not triger pattern check
alibaba/form-render pull request #156
Opened 2020-09-12 09:20 UTC by zhangchen915

close #150

2020-09-12 09:21 UTC, zhangchen915 commented on src/base/utils.js
> +  if (param1 == null || param2 == null) return param1 === param2;
简化了一下对比 undefined 和 null 逻辑

2020-09-14 12:17 UTC, FateRiddle requested changes
31 行删了有问题。而且个人觉得代码写笨一点，更容易一眼看懂不需要想，好维护。

2020-09-14 12:17 UTC, FateRiddle commented on src/base/utils.js
> -  if (param1 === undefined && param2 === undefined) return true;
为啥把这行删了？

2020-09-15 02:42 UTC, zhangchen915 commented on src/base/utils.js
> -  if (param1 === undefined && param2 === undefined) return true;
😂  因为，`undefined == null ` 为 true

2020-09-16 03:18 UTC, zhangchen915 commented
> 31 行删了有问题。而且个人觉得代码写笨一点，更容易一眼看懂不需要想，好维护。

已经还原回去了

2020-09-21 09:30 UTC, closed without merging